### PR TITLE
Support for marketing automation

### PR DESCRIPTION
**Pull request by devyoustice**
Among other minor changes and bugfixes, this pull request enables automating the marketing and support follow-up after installtion/configuration.

### CODE REVIEW

**Comment by devyoustice** [comment]
Hi, please have a look on this.

**Comment by devyoustice** [comment]
Hi, any update on this?

**Comment by devyoustice** [comment]
kind reminder: this pull request is still waiting for you to merge.

**Comment by devyoustice** [comment]
Infinario removed. Hope it's ok now for approval.

**Comment by Quetzacoalt91** [comment]
Hi @devyoustice,

I have just tested the PR before merging it and I got the following message when I try to report a product:
> Connection to remote server failed, please __try again__ later

Are the different APIs working properly ?

**Comment by devyoustice** [comment]
Which operation was it, exactly? The APIs are all up and our prestashop demo-site works just ok with this version. Can it be a networking restriction on your end?

**Comment by Quetzacoalt91** [comment]
Hi @devyoustice,

This is when I try to create a claim on a specific product.
capture du 2015-10-15 17 41 29

This message appears when an exception is thrown, so I will show it.

**Comment by devyoustice** [comment]
APi key is for SANDBOX or PROD?

**Comment by Quetzacoalt91** [comment]
Sandbox

**Comment by devyoustice** [comment]
paste here the first 10 chars of the API key please.

**Comment by Quetzacoalt91** [comment]
Here they are: 0916571317

**Comment by devyoustice** [comment]
The calls reach us and are returned with HTTP-200.

**Comment by Quetzacoalt91** [comment]
Strange, here is my Exception output:

```
YousticeFailedRemoteConnectionException Object 
( 
      [code:protected] => 100 
      [message:protected] => Post Request failed: Api/addTransaction 
      [string:Exception:private] => 
      [file:protected] => /home/modules/www/public_html/prestashop-15/modules/yousticeresolutionsystem/SDK/Request.php
      [line:protected] => 95
)
```

**Comment by devyoustice** [comment]
I've just noticed that on this repository a lot of folders remained and were not deleted. No idea why. I'll push a cleanup commit.

**Comment by Quetzacoalt91** [comment]
Okay, let me know when I can try again.

**Comment by devyoustice** [comment]
Compare this with the original: https://github.com/devyoustice/yousticeresolutionsystem

**Comment by devyoustice** [comment]
Ah, I see. the 'master' still reflects version 1.8.5

**Comment by devyoustice** [comment]
there should be a detailed error logged (as a result of line Request.php, line: 93).

**Comment by Quetzacoalt91** [comment]
FYI

> Youstice - remote request failed 
> [url]: POST Api/addTransaction 
> [request]: {"orderNumber":"2__3__10","itemDescription":"<p><span style=\"font-size: small;\">

> [...]

><span style=\"font-size: small;\">La musique en technicolor.<\/span><\/strong><\/p>\r\n<p>iPod shuffle s'affiche d\u00e9sormais dans de nouveaux coloris intenses qui rehaussent le design \u00e9pur\u00e9 du bo\u00eetier en aluminium anodis\u00e9. Choisissez parmi le bleu, le vert, le rose, le rouge et l'argent\u00e9 d'origine.<\/.<\\\/span><\\\/strong><\\\/p>\\r\\n<p>iPod shuffle s'affiche d\\u00e9sormais dans de nouveaux coloris intenses qui rehaussent le design \\u00e9pur\\u00e9 du bo\\u00eetier en aluminium anodis\\u00e9. Choisissez parmi le bleu, le vert, le rose, le rouge et l'argent\\u00e9 d'origine.<\\\/p>\",\"description_short\":\"<p>iPod shuffle, le baladeur le plus portable du monde, se clippe maintenant en bleu, vert, rose et rouge.<\\\/p>\",\"price\":\"66.053500\",\"reference\":\"demo_2\",\"ean13\":\"0\",\"width\":\"0.000000\",\"height\":\"0.000000\",\"depth\":\"0.000000\",\"weight\":\"0.000000\",\"supplier_name\":\"AppleStore\"}}"} 
> [response]: {"orders":[]}

**Comment by devyoustice** [comment]
Seems to be a problem with some unquoted character. That is, the itemDescription object contains something that is not handled well by the plugin.

**Comment by devyoustice** [comment]
Yeah, the line feed characters (CHAR(10)) are not liked by the JSON parser.

**Comment by Quetzacoalt91** [comment]
Hi @devyoustice,

You investigated on the issue, but what would you like to do before I can merge this PR ?
Will you remove the itemDescription ?

**Comment by devyoustice** [comment]
Wait for the updated version please. Proper escaping will be added and itemDescription will be removed from the data sent.

**Comment by devyoustice** [comment]
Try this version please. Also please upload the former error report somewhere as a gist so all the chars are correctly preserved.

**Comment by Quetzacoalt91** [comment]
Hi,

Fortunately the error does not appear anymore, so I can merge your PR if you want to.
And which report are you talking about exactly ?

**Comment by devyoustice** [comment]
Thank you. Error report: the one starting with
```
Youstice - remote request failed 
[url]: POST Api/addTransaction 
[request]: {"orderNumber":"2__3__10","itemDescription":"
```
from your comment in https://github.com/PrestaShop/yousticeresolutionsystem/pull/28#issuecomment-148445865

**Comment by Quetzacoalt91** [comment]
Hmm, still trying to get the issue again, but without success.
Did you change your API ? I am currently on the commit which brought me the issue. :neutral_face:

**Comment by Quetzacoalt91** [comment]
FYI, I do not accept any PR on Fridays. I can merge yours today, or you will have to wait for next week. :wink:

**Comment by devyoustice** [comment]
That is intriguing. There was no change on the API side for the last 15 days.

**Comment by devyoustice** [comment]
So can we merge this now?

**Comment by Quetzacoalt91** [comment]
Hi @devyoustice,

Yeah, I double checked that everything was like in the PR.
And I was waiting for your go. :wink:

**Comment by Quetzacoalt91** [comment]
Hi again,

The PR has just been merged and the changes should be available soon.

Best regards

**Comment by devyoustice** [comment]
Ah OK. Thanks for merging.

**Pull request merged**
