### PR TITLE
Resilience against non-standard templates

### PR DESCRIPTION
**Pull request by devyoustice**
resilience against non-standard templates.
If the order-history entry-point to show our extra buttons is not found, show a custom-made order page with our buttons.

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi,

Moving the js function showProductsButtons() in the jquery Context throws the following error when I click on the button Order details:
capture du 2015-01-12 10 45 49

**Comment by devyoustice** [comment]
Could you please try that once again? Chances are it was caused by our API server on SANDBOX.

**Comment by Quetzacoalt91** [comment]
Unfortunately, the problem still occurs and cannot get order details on the front office anymore.

**Comment by devyoustice** [comment]
Your checkout is likely incomplete.
See yrs_order_history.js in https://github.com/devyoustice/yousticeresolutionsystem/commit/d51598898a97ec96fe062b4a18a54e1346a4dd43. The change clearly marks the definition of 
showProductsButtons in yrs_order_history.js, line 9.

**Comment by Quetzacoalt91** [comment]
Sorry @devyoustice, but I can only find l.9 a variable definition, not a function one. :)

I am talking about the function ```showProductsButtons()``` which cannot be called anymore because you move its definition in the jQuery context. And even if you go back in this context before calling the function, it does not work. :/

**Comment by devyoustice** [comment]
interesting. The Function is on line 111. And I still don't get, how come it works for us (and I double checked the commit - there are no differences). Does an uninstall/reinstall of the plugin help?

**Comment by Quetzacoalt91** [comment]
Uninstalled and reinstalled but still not working. However, I may find a solution in *js/yrs_order_history.js*:
```js
jQuery(function($) {
    showProductsButtons = function() {
        [...]
    };
}
```

**Comment by devyoustice** [comment]
Let's try with this updated pull request. Commit c90eb8 could likely fix the JS problem. The rest is translations and CSS.

**Comment by Quetzacoalt91** [comment]
Hi,

I did not see the commit but indeed, it fixed the issue.
The PR has just been merged, thanks.

Regards

**Pull request merged**
