### PR TITLE
PHP 5.3 compatibility and multilingual config.xml files

### PR DESCRIPTION
**Pull request by devyoustice**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @devyoustice,

Can you please remove all localized config files ?

Thanks

**Comment by devyoustice** [comment]
Sure, we can do so. Please elaborate why that would be recommended?

**Comment by Quetzacoalt91** [comment]
We ask for the config.xml file in order to use the cache available on PrestaShop, but we do not require localized config files because they are not always needed (regarding the current language of the employee).
We try to balance between the optimization and the amount of file stored in the repository, that's we only require the default config.xml, in english. 

Regards

**Comment by devyoustice** [comment]
will create a new one instead of this with more functionality added.

**Pull request closed without merging**
